# Generated by Django 3.2.7 on 2021-09-16 14:28

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_phonebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonebook',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
